//
// records.ts - generic class for health records which may contain documents, reports, biomarker measurements, etc.
//

import { Page } from "../scan/ocr"
import { Measurement } from "./biomarkers"
import { Metadata } from "./items"
import { Content } from "./contents"

export const RECORD_TYPE = "record"
export const RECORD_PREFIX = "rcd_"

/**
 * A health record is a piece of content which may include a textual part
 * with title, description and markup contents, a number of references,
 * attached documents, scanned pages (ocr) and biomarker results. A health
 * record may be entered directly or automatically generated by scanning one
 * or more pdf documents, etc.
 */
export class Record extends Content {
  constructor() {
    super()
    this.id = Record.generateId()
    this.type = RECORD_TYPE
  }

  /** Define content type  */
  public static get itemType(): string {
    return RECORD_TYPE
  }

  /** Id prefix to be used for this kind of items */
  public static get itemPrefix(): string {
    return RECORD_PREFIX
  }

  /** Pages in this report with fulltext, OCR words, etc */
  pages?: Page[]

  /** Biomarker measurements detected in this report */
  measurements?: Measurement[]

  /** Additional metadata on this report */
  metadata: Metadata
}
