# Commands to build base docker image used to speed up subsequent cloud builds
# this image should be refreshed every once in a while (when packages change)
# Based on the official lightweight Node.js image

FROM node:16-slim
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install

# Update this image:
# docker build -t "eu.gcr.io/biomarkers-app/biomarkers-base" . -f Dockerfile-base && docker push eu.gcr.io/biomarkers-app/biomarkers-base
