name: "Yarn Tests"
on: push

defaults:
  run:
    working-directory: app

jobs:
  build:
    name: "Jest Tests"
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run tests
      run: yarn test