name: "Jest Tests"
on: push

defaults:
  run:
    working-directory: app

jobs:
  build:
    name: "Jest Tests"
    runs-on: ubuntu-latest
    environment: Preview
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run tests
      env: # as an environment variable
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      run: yarn test
    - name: Archive test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/test-report.html
        retention-days: 7